export const tips = [
  {
    id: 1,
    titulo: "Empieza por una funcionalidad, no por el layout",
    desc: "No empieces diseñando el menú de navegación o el footer. Comienza con la característica principal que el usuario vino a usar en esa pantalla y construye hacia afuera.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo1.html",
  },
  {
    id: 2,
    titulo: "No encierres todo en cajas",
    desc: "Evita usar demasiados bordes para separar contenido. Si todo está en una caja, la interfaz se siente desordenada. Usa espacios en blanco (margin/padding) para agrupar elementos.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo2.html",
  },
  {
    id: 3,
    titulo: "Usa el espaciado para establecer relaciones",
    desc: "Los elementos que están relacionados lógicamente deben estar más cerca visualmente. Si un título pertenece a un párrafo, el espacio debajo del título debe ser menor que el espacio arriba de él.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo3.html",
  },
  {
    id: 4,
    titulo: "Enfatiza quitando énfasis al resto",
    desc: "A veces, para hacer que un elemento resalte (como un texto importante), no necesitas hacerlo más grande o más oscuro. En su lugar, haz que los elementos secundarios sean más claros o pequeños.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo4.html",
  },
  {
    id: 5,
    titulo: "El tamaño del texto no es la única jerarquía",
    desc: "No dependas solo de 'font-size' para la jerarquía. Usa el peso de la fuente (bold, medium), el color (gris para menor importancia) y el espaciado para guiar el ojo del usuario.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo5.html",
  },
  {
    id: 6,
    titulo: "Evita el texto gris sobre fondos de color",
    desc: "Si tienes un fondo azul y quieres un texto secundario, no uses gris. Usa un azul más claro o más oscuro. El texto gris solo se ve bien sobre fondos blancos o casi negros.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo6.html",
  },
  {
    id: 7,
    titulo: "Usa menos bordes, más sombras y fondos",
    desc: "En lugar de usar bordes duros para separar elementos, intenta usar un fondo ligeramente diferente o una sombra suave.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo7.html",
  },
  {
    id: 8,
    titulo: "El color necesita un propósito",
    desc: "No uses colores al azar solo para decorar. Usa tu color de acento para acciones (botones, links) y mantén el resto de la interfaz neutral. Esto hace que las llamadas a la acción resalten de verdad.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo8.html",
  },
  {
    id: 9,
    titulo: "Añade profundidad superponiendo elementos",
    desc: "Las interfaces planas pueden verse aburridas. Haz que las tarjetas se superpongan ligeramente a un banner de fondo y añade sombras para que parezca que están 'flotando' sobre la página.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo9.html",
  },
  {
    id: 10,
    titulo: "Los íconos no deben competir con el texto",
    desc: "Si usas un ícono junto a un texto, el ícono debe ser de un color más suave que el texto o tener un tratamiento visual más sutil para no robarse toda la atención.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo10.html",
  },
  {
    id: 11,
    titulo: "Diseña en escala de grises primero",
    desc: "Evita distraerte con los colores al principio. Construye la estructura, el espaciado y la jerarquía en tonos de gris, y añade el color al final.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo11.html",
  },
  {
    id: 12,
    titulo: "El alto de línea no es estático",
    desc: "El texto pequeño necesita más alto de línea (line-height) para ser legible, pero los títulos grandes necesitan menos, o se verán desconectados.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo12.html",
  },
  {
    id: 13,
    titulo: "Limita el ancho de los párrafos",
    desc: "Un texto muy ancho cansa la vista. Mantenlo entre 45 y 75 caracteres por línea. Usa 'max-w-prose' o medidas similares en Tailwind.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo13.html",
  },
  {
    id: 14,
    titulo: "Alinea los números a la derecha",
    desc: "En tablas o listas con cifras, alinear los números a la derecha facilita que el usuario compare valores y lea las unidades rápidamente.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo14.html",
  },
  {
    id: 15,
    titulo: "Usa opacidad para el texto, no colores más claros",
    desc: "En lugar de elegir un gris más claro para el texto secundario, usa opacidad. Así el texto tomará un tinte sutil del color de fondo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo15.html",
  },
  {
    id: 16,
    titulo: "No agrandes íconos solo para llenar espacio",
    desc: "Si un ícono se ve muy pequeño en su contenedor, no lo estires. Ponlo dentro de un círculo o cuadrado con un color de fondo suave.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo16.html",
  },
  {
    id: 17,
    titulo: "Acciones secundarias que se vean secundarias",
    desc: "No uses botones sólidos para todo. Usa fondos transparentes, bordes suaves o solo texto para las acciones menos importantes.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo17.html",
  },
  {
    id: 18,
    titulo: "Diseña para los 'Estados Vacíos' (Empty States)",
    desc: "No dejes una pantalla en blanco si no hay datos o listas vacías. Usa ese espacio para educar al usuario o guiarlo a crear su primer elemento.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo18.html",
  },
  {
    id: 19,
    titulo: "No confíes solo en el 'placeholder'",
    desc: "Cuando el usuario escribe en un input, el placeholder desaparece. Usa siempre etiquetas (labels) arriba para que no olviden qué están llenando.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo19.html",
  },
  {
    id: 20,
    titulo: "Destaca la información, no las etiquetas",
    desc: "En pares de datos (ej. 'Nombre: Lorenzo'), el dato ('Lorenzo') es lo que importa. Hazlo oscuro y en negrita, y deja la etiqueta en gris.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo20.html",
  },
  {
    id: 21,
    titulo: "Sombras realistas en lugar de sombras duras",
    desc: "Evita una sola sombra oscura. Combina múltiples sombras muy suaves y superpuestas para lograr un efecto de elevación mucho más natural.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo21.html",
  },
  {
    id: 22,
    titulo: "Suaviza el blanco puro y el negro puro",
    desc: "El contraste extremo cansa la vista. Usa grises muy oscuros en lugar de negro (#000000) y blancos rotos en lugar de blanco absoluto (#FFFFFF).",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo22.html",
  },
  {
    id: 23,
    titulo: "Personaliza tus viñetas (bullets)",
    desc: "Cambia los aburridos puntos negros de las listas por íconos de 'check', flechas o formas geométricas que usen tu color de acento.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo23.html",
  },
  {
    id: 24,
    titulo: "Agrupa información relacionada",
    desc: "Si tienes muchos datos en una pantalla, no los pongas todos sueltos. Agrúpalos visualmente en tarjetas o secciones bien delimitadas.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo24.html",
  },
  {
    id: 25,
    titulo: "No estires las imágenes, recórtalas",
    desc: "Nunca permitas que una imagen pierda su proporción. Usa la propiedad 'object-cover' para que llenen su contenedor sin deformarse.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo25.html",
  },
  {
    id: 26,
    titulo: "Piensa fuera de la tarjeta blanca",
    desc: "Para destacar un componente importante (como un plan 'Pro'), invierte los colores (fondo oscuro, texto claro) en lugar de solo hacerlo más grande.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo26.html",
  },
  {
    id: 27,
    titulo: "Dale cariño a los estados interactivos",
    desc: "El usuario debe saber exactamente dónde está el mouse o el teclado. Que tus botones e inputs cambien claramente en 'hover' y 'focus'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo27.html",
  },
  {
    id: 28,
    titulo: "Reemplaza divisores con colores de fondo",
    desc: "En lugar de usar líneas sólidas (<hr />) entre dos secciones grandes, dale a una de ellas un fondo ligeramente distinto para separarlas visualmente.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo28.html",
  },
  {
    id: 29,
    titulo: "Asegura el contraste en imágenes de fondo",
    desc: "No confíes en que la imagen siempre será oscura. Añade un degradado negro translúcido detrás del texto para que siempre sea legible.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo29.html",
  },
  {
    id: 30,
    titulo: "Las tablas no siempre necesitan cuadrículas",
    desc: "Usa fondos sutiles por fila (cebreado) o simplemente buen espaciado en blanco en lugar de dibujar bordes pesados en cada celda.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo30.html",
  },
  {
    id: 31,
    titulo: "Usa una escala para todo",
    desc: "No elijas valores al azar. Define una escala para tamaños de fuente, espaciado, anchos y sombras. Esto crea una armonía visual que el usuario percibe inconscientemente.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo31.html",
  },
  {
    id: 32,
    titulo: "Añade 'Letter-spacing' a los textos en mayúsculas",
    desc: "El texto en 'ALL CAPS' es más difícil de leer porque todas las letras tienen la misma altura. Añadir un poco de tracking (espacio entre letras) lo hace mucho más elegante y legible.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo32.html",
  },
  {
    id: 33,
    titulo: "No uses 'Ghost Buttons' para acciones principales",
    desc: "Los botones con solo borde desaparecen visualmente. Úsalos solo para acciones muy secundarias. La acción principal siempre debe tener un fondo sólido y llamativo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo33.html",
  },
  {
    id: 34,
    titulo: "El texto pequeño necesita más peso",
    desc: "Si usas una fuente muy fina en tamaños pequeños, se volverá invisible en pantallas de baja resolución. Sube el 'font-weight' a medium o semibold para compensar.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo34.html",
  },
  {
    id: 35,
    titulo: "La jerarquía no es solo tamaño",
    desc: "Puedes crear jerarquía usando el color, el peso de la fuente y el espaciado. A veces, un texto pequeño en negrita destaca más que uno grande y fino.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo35.html",
  },
  {
    id: 36,
    titulo: "Usa bordes internos para definir formas",
    desc: "En elementos oscuros, un borde interno de 1px ligeramente más claro que el fondo ayuda a definir la silueta del componente sin que parezca un trazo pesado.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo36.html",
  },
  {
    id: 37,
    titulo: "No todos los íconos necesitan el mismo peso",
    desc: "Si usas un ícono muy 'relleno' junto a uno lineal, el diseño se verá desequilibrado. Intenta que todos tus íconos compartan el mismo estilo visual y grosor de línea.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo37.html",
  },
  {
    id: 38,
    titulo: "Evita los selectores infinitos",
    desc: "Si tienes una lista desplegable con 50 opciones, mejor usa un input de búsqueda con autocompletado. No obligues al usuario a hacer scroll infinito.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo38.html",
  },
  {
    id: 39,
    titulo: "Las sombras deben ser de colores",
    desc: "En lugar de usar negro con opacidad para las sombras, usa una versión muy oscura del color de fondo o del color del elemento. Se ve mucho más orgánico.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo39.html",
  },
  {
    id: 40,
    titulo: "Alinea visualmente, no solo matemáticamente",
    desc: "A veces, el centro matemático de un ícono no es el centro visual (como el triángulo de un botón de 'Play'). Ajusta manualmente hasta que 'se sienta' centrado.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo40.html",
  },
  {
    id: 41,
    titulo: "Simplifica los formularios complejos",
    desc: "Si un formulario tiene muchos campos, divídelo en pasos o agrupa los campos relacionados en secciones con títulos claros para no abrumar al usuario.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo41.html",
  },
  {
    id: 42,
    titulo: "Usa el color para indicar estados, no solo decoración",
    desc: "Reserva el rojo para errores, el verde para éxitos y el amarillo para advertencias. No uses estos colores para otros elementos o confundirás al usuario.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo42.html",
  },
  {
    id: 43,
    titulo: "La consistencia en los bordes es clave",
    desc: "No mezcles 'rounded-sm' con 'rounded-full' sin motivo. Mantén un radio de borde consistente en toda la app para que todos los componentes parezcan de la misma familia.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo43.html",
  },
  {
    id: 44,
    titulo: "Diferencia entre 'Seleccionado' y 'En foco'",
    desc: "Un elemento seleccionado debe verse distinto a un elemento que simplemente tiene el foco del teclado. Usa bordes o anillos de color diferentes para cada estado.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo44.html",
  },
  {
    id: 45,
    titulo: "No uses sombras en elementos pequeños",
    desc: "Las sombras en elementos muy pequeños suelen verse sucias o borrosas. Guarda las sombras para tarjetas, modales y componentes grandes que necesiten elevación.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo45.html",
  },
  {
    id: 46,
    titulo: "Proporciona feedback inmediato",
    desc: "Cuando un usuario hace clic en algo, debe pasar algo. Aunque sea un pequeño cambio de color o un spinner de carga, el usuario debe saber que su acción fue recibida.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo46.html",
  },
  {
    id: 47,
    titulo: "Usa 'Skeletons' en lugar de Spinners",
    desc: "Para cargas largas, los skeleton screens (formas grises que imitan el contenido) reducen la percepción del tiempo de espera comparado con un círculo dando vueltas.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo47.html",
  },
  {
    id: 48,
    titulo: "El espaciado negativo es tu aliado",
    desc: "No tengas miedo de dejar grandes espacios vacíos. El 'aire' ayuda a que el usuario se concentre en lo importante y hace que la interfaz se sienta de alta gama.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo48.html",
  },
  {
    id: 49,
    titulo: "Mantén los botones de acción cerca de los inputs",
    desc: "No pongas el botón de 'Guardar' en la esquina opuesta de donde el usuario terminó de escribir. Minimiza el movimiento que el usuario debe hacer con el mouse.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo49.html",
  },
  {
    id: 50,
    titulo: "Menos es más: elimina lo innecesario",
    desc: "Si un elemento no ayuda al usuario a completar su tarea o no comunica información valiosa, quítalo. La mejor interfaz es la que tiene solo lo justo y necesario.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo50.html",
  },
  {
    id: 51,
    titulo: "Limítate a una sola familia de fuentes",
    desc: "No necesitas dos fuentes distintas para que un diseño se vea bien. Jugar con el peso (bold, light), el color y el tamaño de una sola fuente suele ser suficiente y mantiene la armonía.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo51.html",
  },
  {
    id: 52,
    titulo: "Ajusta el radio de borde interno",
    desc: "Si tienes una tarjeta con bordes redondeados y un elemento dentro con bordes, el radio interno debe ser menor que el externo. La fórmula ideal es: 'Radio Externo - Padding = Radio Interno'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo52.html",
  },
  {
    id: 53,
    titulo: "No centres bloques largos de texto",
    desc: "El texto centrado es difícil de leer si tiene más de tres líneas porque el ojo tiene que buscar el inicio de cada fila. Para párrafos largos, usa siempre alineación a la izquierda.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo53.html",
  },
  {
    id: 54,
    titulo: "Dale temperatura a tus grises",
    desc: "En lugar de usar grises puros (#888888), añade un toque de azul para grises 'fríos' o un toque de amarillo/marrón para grises 'cálidos'. Esto hace que el diseño se sienta más vivo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo54.html",
  },
  {
    id: 55,
    titulo: "Alineación óptica en botones",
    desc: "A veces, el centro matemático no es el centro visual. Por ejemplo, en un botón de 'Play', el triángulo debe desplazarse un poco a la derecha para que parezca realmente centrado.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo55.html",
  },
  {
    id: 56,
    titulo: "Objetivos táctiles (Touch Targets)",
    desc: "En móviles, asegúrate de que cualquier elemento clickeable tenga al menos 44x44 píxeles. No hay nada más frustrante para un usuario que un botón demasiado pequeño para su dedo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo56.html",
  },
  {
    id: 57,
    titulo: "Evita layouts excesivamente anchos",
    desc: "En pantallas grandes, no dejes que el contenido se estire hasta los bordes. Usa un contenedor con un 'max-width' para mantener la información fácil de escanear.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo57.html",
  },
  {
    id: 58,
    titulo: "Superposición para crear profundidad",
    desc: "Para que una interfaz no se sienta plana, haz que los elementos se superpongan ligeramente. Un modal que sobresale o una imagen que rompe la línea de un contenedor añade dinamismo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo58.html",
  },
  {
    id: 59,
    titulo: "Contraste sin sacrificar la estética",
    desc: "Si necesitas más contraste para accesibilidad, no solo oscurezcas el color. Prueba aumentando la saturación o cambiando ligeramente el tono para que el color siga siendo atractivo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo59.html",
  },
  {
    id: 60,
    titulo: "Terminología consistente",
    desc: "Si en una pantalla usas 'Guardar', no uses 'Enviar' en otra para la misma acción. La consistencia en el lenguaje reduce la carga cognitiva del usuario.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo60.html",
  },
  {
    id: 61,
    titulo: "Usa contenido real, no Lorem Ipsum",
    desc: "El diseño cambia drásticamente cuando usas nombres reales o fotos reales. El 'Lorem Ipsum' suele ocultar problemas de espacio que solo verás cuando la app esté en producción.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo61.html",
  },
  {
    id: 62,
    titulo: "Diseño accesible para daltónicos",
    desc: "No confíes solo en el color para dar mensajes. Si hay un error, usa el color rojo PERO también un ícono de advertencia. El color debe ser un refuerzo, no la única señal.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo62.html",
  },
  {
    id: 63,
    titulo: "El sistema de rejilla de 8px",
    desc: "Usa múltiplos de 8 para tus paddings y margins (8, 16, 24, 32...). Esto crea un ritmo visual perfecto y hace que las decisiones de espaciado sean mucho más rápidas.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo63.html",
  },
  {
    id: 64,
    titulo: "Relaciones de aspecto consistentes",
    desc: "Mantén tus imágenes en proporciones estándar como 16:9, 4:3 o 1:1. Usar medidas aleatorias hace que la interfaz se sienta desorganizada.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo64.html",
  },
  {
    id: 65,
    titulo: "Manejo de contenido largo",
    desc: "Diseña pensando en qué pasa si un nombre es muy largo. ¿Se corta con puntos suspensivos? ¿Baja a la siguiente línea? No asumas que los datos siempre serán cortos.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo65.html",
  },
  {
    id: 66,
    titulo: "Sombras en modo oscuro",
    desc: "En modo oscuro, las sombras deben ser más oscuras que el fondo, no más claras. La elevación se nota porque el elemento es ligeramente más claro que el fondo, no por la sombra.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo66.html",
  },
  {
    id: 67,
    titulo: "Indicadores de navegación clara",
    desc: "El usuario siempre debe saber en qué página está. Resalta el link actual en tu menú con un color distinto, un subrayado o un cambio de grosor en la fuente.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo67.html",
  },
  {
    id: 68,
    titulo: "No ocultes info esencial tras el hover",
    desc: "En dispositivos móviles no existe el 'hover'. Si escondes información importante que solo aparece al pasar el mouse, los usuarios de tablet y celular nunca la verán.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo68.html",
  },
  {
    id: 69,
    titulo: "Fuentes del sistema para rendimiento",
    desc: "A veces, usar la fuente nativa del sistema (San Francisco en iOS, Roboto en Android) es mejor que cargar una fuente pesada de Google Fonts. Es instantáneo y familiar.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo69.html",
  },
  {
    id: 70,
    titulo: "El branding es el detalle, no la base",
    desc: "No fuerces tu logo o colores de marca en cada rincón. Una interfaz limpia donde la marca aparece sutilmente en botones o acentos es mucho más profesional.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo70.html",
  },
  {
    id: 71,
    titulo: "No uses colores aleatorios, usa una paleta",
    desc: "No elijas colores sobre la marcha. Define 5-9 tonos de cada color (50, 100, 200...) y cíñete a ellos. Esto garantiza que el contraste sea predecible en toda la interfaz.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo71.html",
  },
  {
    id: 72,
    titulo: "Diferencia las acciones primarias y secundarias",
    desc: "El botón de 'Eliminar' y 'Guardar' no deben competir. Usa un estilo sólido para la acción principal y un estilo de borde o solo texto para la secundaria.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo72.html",
  },
  {
    id: 73,
    titulo: "El margen negativo para romper la cuadrícula",
    desc: "A veces, mover un ícono un poco hacia afuera de su contenedor con un margen negativo hace que el diseño se sienta más orgánico y menos 'atrapado' en cajas.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo73.html",
  },
  {
    id: 74,
    titulo: "Optimiza para el escaneo visual",
    desc: "Los usuarios no leen, escanean. Usa títulos claros, listas con viñetas y negritas en palabras clave para que el usuario encuentre lo que busca en segundos.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo74.html",
  },
  {
    id: 75,
    titulo: "El texto grande necesita menos peso",
    desc: "A medida que aumentas el tamaño de la fuente, esta se ve más gruesa de lo que es. Baja el 'font-weight' en los encabezados grandes para que se vean refinados.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo75.html",
  },
  {
    id: 76,
    titulo: "Íconos con etiquetas para acciones complejas",
    desc: "Un ícono de 'engranaje' es universal, pero uno de 'rama' puede no serlo. Si la acción no es obvia, acompaña siempre el ícono con un texto descriptivo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo76.html",
  },
  {
    id: 77,
    titulo: "Degradados sutiles para evitar la planitud",
    desc: "Un degradado casi imperceptible (ej. de un gris oscuro a uno un poco más oscuro) da una sensación de calidad y profundidad que un color sólido no puede lograr.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo77.html",
  },
  {
    id: 78,
    titulo: "Bordes de 1px, siempre",
    desc: "Los bordes de 2px suelen verse toscos. Usa bordes de 1px con un color muy suave para lograr un acabado mucho más limpio.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo78.html",
  },
  {
    id: 79,
    titulo: "Espacios en blanco para separar grupos lógicos",
    desc: "No necesitas líneas para separar todo. Un espacio en blanco generoso entre secciones comunica 'aquí termina un tema y empieza otro' de forma más elegante.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo79.html",
  },
  {
    id: 80,
    titulo: "Divulgación Progresiva",
    desc: "No muestres todas las opciones de configuración a la vez. Oculta lo avanzado tras un botón de 'Más opciones' para mantener la interfaz simple para la mayoría.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo80.html",
  },
  {
    id: 81,
    titulo: "Contraste de tamaño y peso combinados",
    desc: "Para que un título resalte sobre un subtítulo, no solo lo hagas más grande. Hazlo también más grueso (bold) y el subtítulo un poco más claro (gris).",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo81.html",
  },
  {
    id: 82,
    titulo: "Animaciones con propósito funcional",
    desc: "La animación debe guiar al ojo. Si un menú sale de la izquierda, la animación debe 'empujar' el contenido para que el usuario entienda de dónde vino.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo82.html",
  },
  {
    id: 83,
    titulo: "Estados vacíos que invitan a la acción",
    desc: "Si una lista está vacía, no solo digas 'No hay datos'. Pon un botón que diga 'Crea tu primer elemento' para que el usuario sepa qué hacer a continuación.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo83.html",
  },
  {
    id: 84,
    titulo: "El ancho del input debe sugerir el contenido",
    desc: "Un campo para 'Código Postal' no debe ser tan ancho como uno para 'Dirección'. Ajustar el ancho del input da pistas visuales de lo que se debe escribir.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo84.html",
  },
  {
    id: 85,
    titulo: "Ritmo vertical consistente",
    desc: "Asegúrate de que el espacio entre párrafos, títulos y componentes sea predecible. Si usas 24px entre secciones, úsalo en toda la aplicación.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo85.html",
  },
  {
    id: 86,
    titulo: "Sombras suaves y extendidas",
    desc: "Una sombra con mucho 'blur' y poca opacidad parece una sombra real. Evita las sombras cortas y oscuras que parecen un borde borroso.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo86.html",
  },
  {
    id: 87,
    titulo: "Migas de pan (Breadcrumbs) para jerarquías profundas",
    desc: "Si tu app tiene más de tres niveles de profundidad, usa breadcrumbs. Ayudan al usuario a ubicarse y a volver atrás sin usar el botón del navegador.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo87.html",
  },
  {
    id: 88,
    titulo: "No dependas solo del color para errores",
    desc: "El 8% de los hombres son daltónicos. Si algo está mal, usa un color rojo Y un ícono de error para que la información sea accesible para todos.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo88.html",
  },
  {
    id: 89,
    titulo: "Alineación a la izquierda por defecto",
    desc: "La alineación a la izquierda es la más natural para leer. Reserva el centrado solo para títulos muy cortos o bloques de héroe con poco texto.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo89.html",
  },
  {
    id: 90,
    titulo: "Consistencia mediante componentes",
    desc: "Si necesitas un botón nuevo, no lo crees de cero. Reutiliza tus clases o componentes existentes. La consistencia es lo que hace que una app se sienta sólida.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo90.html",
  },
  {
    id: 91,
    titulo: "No uses 'Pure Black' para textos",
    desc: "El negro absoluto (#000) contra un fondo blanco genera un contraste demasiado fuerte que cansa la vista. Usa un gris muy oscuro (#1a1a1a) para una lectura más natural.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo91.html",
  },
  {
    id: 92,
    titulo: "Alineación de Iconos con Texto",
    desc: "Cuando pongas un ícono junto a una línea de texto, asegúrate de alinearlos al centro óptico. A veces, bajarlos 1px o 2px manualmente hace que se vean mucho más equilibrados.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo92.html",
  },
  {
    id: 93,
    titulo: "Evita los degradados de 'Arcoíris'",
    desc: "Los mejores degradados son sutiles y usan colores cercanos en el círculo cromático. Si vas de azul a verde, asegúrate de que el paso intermedio no se vea grisáceo o sucio.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo93.html",
  },
  {
    id: 94,
    titulo: "Usa el peso de la fuente para estados activos",
    desc: "En un menú de navegación, puedes resaltar la página actual cambiando el peso de 'medium' a 'bold'. Es un indicador visual claro que no requiere colores extra.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo94.html",
  },
  {
    id: 95,
    titulo: "No todos los botones necesitan bordes",
    desc: "Para acciones de navegación sencillas (como 'Cancelar'), un botón de solo texto con un buen hover es suficiente. Deja los bordes y sombras para las acciones que requieren clics.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo95.html",
  },
  {
    id: 96,
    titulo: "La regla de los 3 colores",
    desc: "Intenta que tu interfaz no tenga más de 3 colores principales: uno base (fondo), uno secundario (textos) y uno de acento (acciones). Esto evita que el usuario se sienta abrumado.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo96.html",
  },
  {
    id: 97,
    titulo: "Sombras internas para campos de texto",
    desc: "Una sombra interna (inset) muy suave en los inputs da la sensación de que el campo está 'hundido' en la página, lo cual invita naturalmente al usuario a escribir en él.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo97.html",
  },
  {
    id: 98,
    titulo: "Mantén los modales simples",
    desc: "Un modal no es una página nueva. Úsalo para tareas rápidas. Si el usuario tiene que hacer mucho scroll dentro de un modal, probablemente esa info debería estar en su propia ruta.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo98.html",
  },
  {
    id: 99,
    titulo: "Cuidado con las esquinas redondeadas extremas",
    desc: "Si usas un 'border-radius' muy grande en una tarjeta pequeña, puedes perder espacio útil en las esquinas. Usa radios moderados (12px-24px) para un look moderno pero funcional.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo99.html",
  },
  {
    id: 100,
    titulo: "Tu diseño debe funcionar sin color",
    desc: "Si quitas todo el color y tu interfaz sigue siendo usable y la jerarquía es clara, entonces tienes un diseño sólido. El color debe ser el toque final, no el soporte principal.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo100.html",
  },
  {
    id: 101,
    titulo: "Usa colores suaves para las etiquetas (Badges)",
    desc: "En lugar de usar fondos de colores sólidos y brillantes para las etiquetas, usa un fondo muy claro de tu color base y el texto en una versión oscura del mismo tono.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo101.html",
  },
  {
    id: 102,
    titulo: "Números tabulares para datos dinámicos",
    desc: "Usa 'font-variant-numeric: tabular-nums' en cronómetros o tablas financieras. Esto hace que todos los números tengan el mismo ancho y evita que el texto 'salte' cuando los valores cambian.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo102.html",
  },
  {
    id: 103,
    titulo: "Iniciales cuando no hay foto de perfil",
    desc: "Si un usuario no sube una imagen, no uses el clásico ícono de silueta gris. Usa un fondo de color con las iniciales de su nombre para darle más vida a la interfaz.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo103.html",
  },
  {
    id: 104,
    titulo: "Haz las tarjetas completamente clickeables",
    desc: "Aumenta el área de interacción haciendo que toda la tarjeta (card) sea un enlace, en lugar de obligar al usuario a hacer clic exactamente en el título o en un texto de 'Leer más'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo104.html",
  },
  {
    id: 105,
    titulo: "No escondas el foco (outline: none)",
    desc: "Nunca quites el anillo de foco por defecto de los navegadores sin reemplazarlo por uno personalizado. Es vital para la accesibilidad y la navegación por teclado.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo105.html",
  },
  {
    id: 106,
    titulo: "Acciones destructivas evidentes pero no dominantes",
    desc: "Usa rojo para acciones como 'Borrar'. Sin embargo, si es una acción secundaria, usa texto rojo sin fondo para no robar la atención del botón principal de la pantalla.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo106.html",
  },
  {
    id: 107,
    titulo: "Tooltips solo para información complementaria",
    desc: "Nunca ocultes información vital o requerida dentro de un tooltip. Si el usuario necesita esa información para completar una tarea, debe estar visible en la pantalla.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo107.html",
  },
  {
    id: 108,
    titulo: "Sombras dinámicas al hacer scroll",
    desc: "Mantén tu barra de navegación (navbar) plana al principio, y añádele una sombra sutil mediante JavaScript solo cuando el usuario empiece a hacer scroll hacia abajo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo108.html",
  },
  {
    id: 109,
    titulo: "Simplifica la paginación larga",
    desc: "No muestres 20 números de página seguidos. Muestra la primera, la última, la actual y un par de páginas adyacentes, separando el resto con puntos suspensivos.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo109.html",
  },
  {
    id: 110,
    titulo: "Labels siempre vinculados",
    desc: "Vincula siempre la etiqueta (<label>) con su input correspondiente usando el atributo 'for' y el 'id'. Esto agranda el área táctil, algo crucial para checkboxes y radio buttons.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo110.html",
  },
  {
    id: 111,
    titulo: "Botones estrictamente de una línea",
    desc: "El texto de un botón nunca debe saltar a una segunda línea. Si el texto es muy largo, resúmelo o ensancha el botón, pero mantenlo en una sola línea verticalmente centrada.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo111.html",
  },
  {
    id: 112,
    titulo: "Personaliza Checkboxes y Radios",
    desc: "Los estilos por defecto del navegador para inputs de selección suelen desentonar con diseños modernos. Ocúltalos visualmente y crea los tuyos con CSS para mantener el branding.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo112.html",
  },
  {
    id: 113,
    titulo: "Agrupa columnas en tablas anchas",
    desc: "Si una tabla tiene demasiadas columnas, aplica un color de fondo súper sutil a grupos de columnas relacionadas para facilitar la lectura y el escaneo vertical.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo113.html",
  },
  {
    id: 114,
    titulo: "Evita el texto justificado en la web",
    desc: "El texto justificado crea 'ríos' de espacios en blanco irregulares que dificultan la lectura en pantallas. Usa siempre alineación a la izquierda para bloques de texto.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo114.html",
  },
  {
    id: 115,
    titulo: "Avatares superpuestos para equipos",
    desc: "Para mostrar un grupo de usuarios, superpón ligeramente los avatares añadiéndoles un borde grueso del mismo color que el fondo. Esto ahorra espacio y crea un efecto visual limpio.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo115.html",
  },
  {
    id: 116,
    titulo: "Indicadores de paso (Steppers) evidentes",
    desc: "En formularios de varios pasos, atenúa visualmente los pasos futuros, resalta el actual y usa un ícono de verificación (check) para los pasos ya completados.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo116.html",
  },
  {
    id: 117,
    titulo: "Feedback descriptivo en la carga",
    desc: "No dependas solo de un spinner genérico dando vueltas. Añade un texto breve que le diga al usuario exactamente qué está pasando (ej. 'Procesando pago...').",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo117.html",
  },
  {
    id: 118,
    titulo: "Menús desplegables con marcas de selección",
    desc: "En un dropdown personalizado, no te limites a cambiar el fondo del elemento seleccionado. Añade un ícono de 'check' al lado del texto para que el estado activo sea inconfundible.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo118.html",
  },
  {
    id: 119,
    titulo: "Texto claro en modo oscuro, no blanco puro",
    desc: "El blanco absoluto (#FFFFFF) sobre fondos oscuros tiene un contraste demasiado alto y causa fatiga visual o un efecto de 'halo'. Usa un gris muy claro o blanco roto en su lugar.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo119.html",
  },
  {
    id: 120,
    titulo: "Esconde los ceros innecesarios",
    desc: "En tablas de precios o paneles de datos, si los decimales son irrelevantes o siempre '.00', elimínalos para limpiar el ruido visual (muestra '$50' en lugar de '$50.00').",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo120.html",
  },
  {
    id: 121,
    titulo: "Usa controles segmentados para pocas opciones",
    desc: "Si un select o dropdown tiene solo entre 2 y 4 opciones, usa un grupo de botones (segmented control). Ahorra un clic y hace que todas las opciones sean visibles de un vistazo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo121.html",
  },
  {
    id: 122,
    titulo: "Alinea los títulos de tabla con sus datos",
    desc: "Si en una tabla los números están alineados a la derecha, el encabezado de esa columna también debe ir a la derecha. Mantén el eje visual recto.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo122.html",
  },
  {
    id: 123,
    titulo: "Toggles vs Checkboxes",
    desc: "Usa interruptores (toggles) para configuraciones que se aplican inmediatamente. Usa checkboxes si el usuario necesita presionar un botón de 'Guardar' al final del formulario.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo123.html",
  },
  {
    id: 124,
    titulo: "Suaviza los bordes de los inputs inactivos",
    desc: "No uses bordes oscuros para los inputs por defecto; pueden saturar la vista. Hazlos sutiles y reserva el contraste fuerte o el anillo de color para el estado ':focus'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo124.html",
  },
  {
    id: 125,
    titulo: "Cuidado con los formularios a múltiples columnas",
    desc: "A menos que sean datos muy relacionados (como Nombre y Apellido), mantén los campos del formulario en una sola columna. Crea un camino de lectura vertical claro y reduce la carga cognitiva.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo125.html",
  },
  {
    id: 126,
    titulo: "Usa verbos claros en los botones",
    desc: "Evita los botones genéricos de 'Enviar' o 'Aceptar'. El botón debe describir exactamente qué pasará al hacer clic: 'Crear cuenta', 'Eliminar proyecto', 'Suscribirse'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo126.html",
  },
  {
    id: 127,
    titulo: "Bordes sutiles para imágenes claras",
    desc: "Si una imagen tiene mucho blanco y se coloca sobre una página blanca, ponle un borde interno casi transparente (ej. negro al 5%). Evitará que la imagen se pierda en el fondo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo127.html",
  },
  {
    id: 128,
    titulo: "Desatura los colores de acento en Modo Oscuro",
    desc: "Los colores puros y brillantes vibran molestamente contra fondos oscuros. Usa versiones más desaturadas (tonos pastel) para mantener el confort visual.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo128.html",
  },
  {
    id: 129,
    titulo: "Formatea los datos visualmente por el usuario",
    desc: "No obligues a escribir números de tarjeta o teléfono con guiones. Deja que el usuario escriba libremente y usa código para separar los bloques de números en la interfaz.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo129.html",
  },
  {
    id: 130,
    titulo: "Botones full-width solo en dispositivos móviles",
    desc: "Un botón que ocupa el 100% del ancho es excelente en móvil para tocarlo fácil, pero en escritorio se ve desproporcionado. Limita su ancho máximo (max-width).",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo130.html",
  },
  {
    id: 131,
    titulo: "Resta importancia al símbolo de moneda",
    desc: "Al mostrar precios, el número es lo que importa. Haz que el símbolo del dólar ($) y los centavos sean ligeramente más pequeños o de un tono más claro.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo131.html",
  },
  {
    id: 132,
    titulo: "Da pistas visuales en elementos con scroll",
    desc: "Si tienes una fila de tarjetas que se puede deslizar horizontalmente, asegúrate de que la última tarjeta visible quede cortada por la mitad. Esto es una pista visual obvia de que hay más contenido.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo132.html",
  },
  {
    id: 133,
    titulo: "Aísla las acciones destructivas (Danger Zone)",
    desc: "En paneles de configuración, aleja acciones como 'Eliminar cuenta' del resto. Agrúpalas en una sección separada con alertas visuales (bordes rojos) para evitar clics accidentales.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo133.html",
  },
  {
    id: 134,
    titulo: "Usa fechas relativas para eventos recientes",
    desc: "Para el usuario es más fácil procesar 'Hace 2 horas' que '12/03/2026 12:43'. Usa fechas relativas para lo reciente y fechas exactas para lo antiguo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo134.html",
  },
  {
    id: 135,
    titulo: "Añade copiar al portapapeles a datos largos",
    desc: "Para tokens, IDs o enlaces, añade un ícono o botón de 'Copiar'. No obligues al usuario a arrastrar el cursor para intentar seleccionar un texto complejo sin equivocarse.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo135.html",
  },
  {
    id: 136,
    titulo: "Inputs grises sobre fondos blancos",
    desc: "En lugar de un input blanco con borde oscuro sobre fondo blanco, intenta quitar el borde y usar un fondo gris muy suave. Se ve mucho más limpio y moderno.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo136.html",
  },
  {
    id: 137,
    titulo: "Las mayúsculas no son para oraciones largas",
    desc: "El texto en 'ALL CAPS' ralentiza la lectura porque todas las letras tienen la misma altura y forma. Guárdalo estrictamente para etiquetas cortas o subtítulos breves.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo137.html",
  },
  {
    id: 138,
    titulo: "Anima las transiciones de estado",
    desc: "Los cambios instantáneos se sienten bruscos. Añade una pequeña transición CSS (ej. 'transition-all duration-200') a los hovers, botones e inputs al recibir foco.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo138.html",
  },
  {
    id: 139,
    titulo: "Equilibra el peso de íconos y tipografía",
    desc: "Si usas una fuente gruesa, usa íconos con líneas gruesas o rellenados (Solid). Si usas una fuente fina, acompáñala con íconos de líneas finas (Light).",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo139.html",
  },
  {
    id: 140,
    titulo: "Los mensajes de error deben ofrecer soluciones",
    desc: "Un mensaje que dice 'Dato inválido' genera frustración. Explica el problema y cómo resolverlo: 'La contraseña debe incluir al menos una mayúscula y un número'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo140.html",
  },
  {
    id: 141,
    titulo: "Alinea los checkboxes arriba con texto multilínea",
    desc: "Si el texto de un checkbox ocupa más de una línea, no centres el checkbox verticalmente. Alinéalo siempre con la primera línea de texto para una lectura natural.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo141.html",
  },
  {
    id: 142,
    titulo: "Añade prefijos y sufijos visuales en los inputs",
    desc: "En lugar de pedirle al usuario que escriba un símbolo de moneda o un dominio, colócalo estáticamente dentro del input (ej. 'https://' o 'kg') como guía visual.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo142.html",
  },
  {
    id: 143,
    titulo: "Destaca lo 'No leído' con indicadores físicos",
    desc: "No confíes solo en poner el texto en negrita para marcar una notificación o mensaje no leído. Añade un punto de color (dot) sólido al lado para que sea inconfundible.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo143.html",
  },
  {
    id: 144,
    titulo: "Agrupa avatares excedentes",
    desc: "Si tienes una lista de 10 usuarios en un proyecto, muestra solo los primeros 3 o 4 avatares superpuestos y reemplaza el resto con un círculo que diga '+6'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo144.html",
  },
  {
    id: 145,
    titulo: "Mantén el ancho del botón durante la carga",
    desc: "Al cambiar el texto de un botón por un 'spinner' de carga, asegúrate de fijar el ancho original del botón mediante CSS para evitar que la interfaz salte.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo145.html",
  },
  {
    id: 146,
    titulo: "Usa 'outline-offset' para los anillos de foco",
    desc: "Cuando un elemento recibe el foco por teclado, separar el anillo del borde del elemento por 1px o 2px (outline-offset) hace que se vea mucho más limpio y moderno.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo146.html",
  },
  {
    id: 147,
    titulo: "Marca la página activa con elementos estructurales",
    desc: "En una barra de navegación, cambiar solo el color del texto a veces no es suficiente. Añade un borde inferior grueso o un fondo sutil a la pestaña activa.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo147.html",
  },
  {
    id: 148,
    titulo: "Permite ver las contraseñas siempre",
    desc: "Añade siempre un ícono de 'ojo' en los inputs de contraseña. Reducirás drásticamente los errores de escritura y la frustración del usuario.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo148.html",
  },
  {
    id: 149,
    titulo: "Muestra atajos de teclado en las barras de búsqueda",
    desc: "Si tu buscador se puede abrir con 'Ctrl + K' o 'Cmd + K', dibuja esas teclas visualmente dentro del propio input para educar a tus usuarios más avanzados.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo149.html",
  },
  {
    id: 150,
    titulo: "Usa 'backdrop-blur' en headers fijos",
    desc: "En lugar de usar un header completamente sólido o 100% transparente, aplica un efecto de desenfoque al fondo (blur). Mantendrá el texto legible mientras dejas ver el scroll.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo150.html",
  },
  {
    id: 151,
    titulo: "Acompaña los puntos de estado con texto",
    desc: "Un círculo verde o rojo no significa nada para un usuario con daltonismo. Acompaña siempre el indicador de color con un texto claro (ej. 'En línea' o 'Desconectado').",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo151.html",
  },
  {
    id: 152,
    titulo: "Reemplaza las flechas nativas de los inputs numéricos",
    desc: "Las flechitas de incremento que traen los navegadores por defecto son demasiado pequeñas. Ocúltalas y crea tus propios botones grandes de '+' y '-' a los lados.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo152.html",
  },
  {
    id: 153,
    titulo: "Acción principal a la derecha, secundaria a la izquierda",
    desc: "En ventanas modales, coloca siempre el botón de acción principal ('Guardar') en la esquina inferior derecha y el de cancelación a su izquierda. Es el estándar al que el ojo está acostumbrado.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo153.html",
  },
  {
    id: 154,
    titulo: "Aplica el 'hover' a toda la fila, no solo al texto",
    desc: "En tablas o listas de opciones, el efecto al pasar el ratón debe iluminar todo el rectángulo de la fila, facilitando el escaneo visual horizontal.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo154.html",
  },
  {
    id: 155,
    titulo: "Haz que el 'padding' del menú sea clickeable",
    desc: "En un menú desplegable, asegúrate de que el área clickeable (el <a> o <button>) incluya el padding, y no se limite solo a las letras del texto.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo155.html",
  },
  {
    id: 156,
    titulo: "Usa íconos inequívocos para expandir/contraer",
    desc: "En los acordeones, usa flechas (chevrons) o signos de '+' y '-' que cambien de estado al hacer clic. No dejes que el usuario adivine si un panel se puede abrir.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo156.html",
  },
  {
    id: 157,
    titulo: "Diferencia claramente las zonas de carga de archivos",
    desc: "Si tienes un área de 'Drag & Drop', usa un borde punteado o discontinuo y un fondo muy claro. Este patrón visual es universal para la carga de archivos.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo157.html",
  },
  {
    id: 158,
    titulo: "No escondas todos los filtros en un 'Dropdown'",
    desc: "Si tienes filtros que se usan constantemente, expón los 2 o 3 más populares como botones rápidos fuera del menú desplegable para ahorrarle clics al usuario.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo158.html",
  },
  {
    id: 159,
    titulo: "Añade un efecto de brillo a tus Skeletons",
    desc: "Los 'Skeleton loaders' estáticos pueden parecer elementos rotos de la interfaz. Añádeles una animación CSS suave (shimmer) que barra de izquierda a derecha para indicar carga.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo159.html",
  },
  {
    id: 160,
    titulo: "Muestra éxito en los inputs, no solo errores",
    desc: "En campos complejos como crear contraseñas o nombres de usuario únicos, muestra un check verde de validación en tiempo real cuando el dato sea correcto, dando feedback positivo inmediato.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo160.html",
  },
  {
    id: 161,
    titulo: "Adapta la densidad al contexto",
    desc: "No abuses del espacio en blanco en paneles de administración. Si el usuario necesita escanear y comparar muchos datos de un vistazo, una interfaz más compacta y densa es más útil.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo161.html",
  },
  {
    id: 162,
    titulo: "Evita palabras huérfanas en los títulos",
    desc: "Usa la propiedad CSS 'text-wrap: balance' en tus encabezados. Esto evita que una sola palabra quede colgando en la última línea, mejorando mucho la estética tipográfica.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo162.html",
  },
  {
    id: 163,
    titulo: "Añade peso físico a los clics",
    desc: "En el estado ':active' de tus botones principales, redúcelos ligeramente (ej. 'scale: 0.98') o trasládalos 1px hacia abajo para dar una sensación táctil satisfactoria al hacer clic.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo163.html",
  },
  {
    id: 164,
    titulo: "Previene la doble sumisión",
    desc: "Deshabilita el botón de 'Enviar' inmediatamente después del primer clic y cambia su estado visual. Esto evita frustraciones, errores de red y cobros dobles en formularios.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo164.html",
  },
  {
    id: 165,
    titulo: "Fija los encabezados en tablas largas",
    desc: "Usa 'position: sticky' en los <th> de tus tablas. Cuando el usuario hace scroll hacia abajo, no debería tener que adivinar qué significa cada columna.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo165.html",
  },
  {
    id: 166,
    titulo: "Auto-enfoca el campo principal",
    desc: "Al abrir un modal de creación o una barra de búsqueda, pon el foco (focus) automáticamente en el primer input. Le ahorras al usuario tener que usar el ratón para empezar a escribir.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo166.html",
  },
  {
    id: 167,
    titulo: "Usa 'Toasts' en lugar de alertas modales",
    desc: "Para mensajes de éxito (ej. 'Proyecto guardado'), no bloquees la pantalla con un modal que requiera un clic para cerrarse. Usa notificaciones flotantes (toasts) que desaparecen solas.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo167.html",
  },
  {
    id: 168,
    titulo: "Estiliza las barras de desplazamiento",
    desc: "Las barras de scroll por defecto del navegador arruinan los diseños limpios, especialmente en Modo Oscuro. Personalízalas con CSS para que coincidan con la paleta de tu app.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo168.html",
  },
  {
    id: 169,
    titulo: "Botón rápido para limpiar búsquedas",
    desc: "Cuando un usuario empieza a escribir en un input de búsqueda, muestra un pequeño ícono de 'X' a la derecha para borrar todo el texto con un solo clic.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo169.html",
  },
  {
    id: 170,
    titulo: "Barras de progreso para tiempos predecibles",
    desc: "Si un proceso tarda más de 3 segundos y sabes cuánto falta (como al subir un archivo), usa una barra de progreso real en lugar de un spinner infinito que genera ansiedad.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo170.html",
  },
  {
    id: 171,
    titulo: "Diferencia las etiquetas de los botones",
    desc: "Si usas componentes tipo 'Badge' o 'Tag' solo para mostrar información, asegúrate de que no tengan efectos 'hover'. Si parecen clickeables, el usuario intentará interactuar con ellos.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo171.html",
  },
  {
    id: 172,
    titulo: "Escala tipográfica exponencial",
    desc: "Los textos pequeños deben aumentar en incrementos pequeños (12px, 14px, 16px), pero los títulos deben saltar drásticamente (24px, 32px, 48px) para lograr un contraste dramático y moderno.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo172.html",
  },
  {
    id: 173,
    titulo: "Marca lo opcional, no lo requerido",
    desc: "Si en un formulario casi todos los campos son obligatorios, es visualmente ruidoso poner un asterisco rojo (*) en todos. Es más limpio marcar solo los campos que dicen '(Opcional)'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo173.html",
  },
  {
    id: 174,
    titulo: "Expón los filtros activos como 'Chips'",
    desc: "Si el usuario aplica filtros dentro de un menú desplegable complejo, muéstrale los filtros seleccionados como pequeñas píldoras (chips) fuera del menú para que sepa exactamente qué está viendo.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo174.html",
  },
  {
    id: 175,
    titulo: "Personaliza el color de selección",
    desc: "Cambia el color azul por defecto de '::selection' por uno que coincida con el color de acento de tu marca o proyecto. Es un detalle sutil que eleva mucho la calidad percibida.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo175.html",
  },
  {
    id: 176,
    titulo: "Enlace invisible para accesibilidad",
    desc: "Añade un enlace oculto al inicio de la página que diga 'Saltar al contenido principal' y que solo sea visible cuando recibe ':focus'. Los usuarios que navegan por teclado te lo agradecerán.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo176.html",
  },
  {
    id: 177,
    titulo: "Botones claros para textos truncados",
    desc: "Si cortas un párrafo usando 'line-clamp', añade siempre un botón explícito de 'Leer más'. No dependas de que el usuario haga clic al azar sobre el texto truncado.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo177.html",
  },
  {
    id: 178,
    titulo: "Interrumpe los divisores con contexto",
    desc: "En lugar de usar dos líneas separadas y un texto en medio, usa flexbox para crear un divisor visual (<hr>) interrumpido por el texto (ej. 'o continúa con Google').",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo178.html",
  },
  {
    id: 179,
    titulo: "Agrupa las notificaciones repetitivas",
    desc: "Si un usuario recibe muchas notificaciones del mismo tipo en poco tiempo, agrúpalas. Es mejor mostrar '5 personas han comentado' que llenar la pantalla con 5 alertas idénticas.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo179.html",
  },
  {
    id: 180,
    titulo: "Fondos de precarga para imágenes",
    desc: "Añade un color de fondo gris claro al contenedor de tus imágenes. Mientras la imagen real se descarga desde la red, la estructura de tu página se mantendrá intacta y no saltará.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo180.html",
  },
  {
    id: 181,
    titulo: "Bordes sutiles en avatares claros",
    desc: "Si el avatar de un usuario tiene un fondo blanco o muy claro, añádele un borde interior casi transparente (ej. negro al 10%) para que no se funda con el fondo de la página.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo181.html",
  },
  {
    id: 182,
    titulo: "Etiquetas directas en los gráficos",
    desc: "En lugar de usar una leyenda separada que obligue al usuario a mover la vista de un lado a otro, coloca el nombre de los datos directamente al final de la línea o barra en el gráfico.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo182.html",
  },
  {
    id: 183,
    titulo: "Ilustraciones de estado vacío sutiles",
    desc: "Las ilustraciones grandes y coloridas cuando no hay datos pueden abrumar. Bájalas de tono, usa opacidad o tonos grises/pastel para que la llamada a la acción siga siendo el foco principal.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo183.html",
  },
  {
    id: 184,
    titulo: "Inputs de texto para fechas lejanas",
    desc: "Nunca obligues al usuario a usar un calendario (Datepicker) para su fecha de nacimiento. Es mucho más rápido escribir '18/09/2004' en un campo de texto con el formato correcto.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo184.html",
  },
  {
    id: 185,
    titulo: "Destaca visualmente el plan recomendado",
    desc: "En tablas de precios, haz que el plan que quieres que elijan resalte del resto: hazlo ligeramente más alto, ponle un borde del color de acento o usa un fondo distinto.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo185.html",
  },
  {
    id: 186,
    titulo: "Colores obvios en los interruptores (Toggles)",
    desc: "Un interruptor encendido debe tener un color afirmativo (generalmente verde o azul). Apagado debe ser un gris neutro. Evita usar el color rojo para apagado, ya que implica 'error'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo186.html",
  },
  {
    id: 187,
    titulo: "Feedback visual en contraseñas",
    desc: "No esperes a que el usuario presione 'Enviar' para decirle que su contraseña es débil. Usa una barra de progreso que cambie de rojo a verde en tiempo real mientras escribe.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo187.html",
  },
  {
    id: 188,
    titulo: "Resalta el término de búsqueda",
    desc: "Cuando muestres resultados de una búsqueda, envuelve el término coincidente con un <mark> o ponlo en negrita. Ayuda al usuario a entender rápidamente por qué ese resultado está ahí.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo188.html",
  },
  {
    id: 189,
    titulo: "Usa 'tokens' para selección múltiple",
    desc: "En lugar de un <select> con opciones múltiples que es difícil de usar, muestra los elementos seleccionados como pequeñas etiquetas (chips/tokens) con una 'x' para eliminarlos fácilmente.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo189.html",
  },
  {
    id: 190,
    titulo: "Cierra modales al hacer clic afuera",
    desc: "Añade un 'backdrop click' (clic en el fondo oscuro). Es el comportamiento esperado y natural para salir de un modal rápidamente sin tener que buscar la pequeña 'X'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo190.html",
  },
  {
    id: 191,
    titulo: "Carga progresiva de imágenes",
    desc: "Carga primero una versión súper comprimida de la imagen y aplícale un filtro CSS 'blur'. Cuando cargue la imagen original pesada, quita el desenfoque suavemente.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo191.html",
  },
  {
    id: 192,
    titulo: "Retraso en la aparición de Tooltips",
    desc: "Aplica un pequeño retraso (delay) de unos 200ms-300ms antes de mostrar un tooltip. Evitarás que aparezcan destellos molestos cuando el usuario simplemente cruza la pantalla con el cursor.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo192.html",
  },
  {
    id: 193,
    titulo: "Abre el teclado correcto en móviles",
    desc: "Si pides un código postal o un PIN, asegúrate de usar 'inputmode=\"numeric\"'. Esto abrirá el teclado de números grandes en los teléfonos, mejorando brutalmente la experiencia.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo193.html",
  },
  {
    id: 194,
    titulo: "Formas distintas para números y estados",
    desc: "Usa píldoras (bordes completamente redondeados) para conteos de números (ej. '5 mensajes'). Usa rectángulos con bordes suaves para estados de texto (ej. 'Completado').",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo194.html",
  },
  {
    id: 195,
    titulo: "Navegación inferior para pantallas móviles",
    desc: "Esconder todo en un menú hamburguesa oculta valor. En móviles, pon las 3 o 4 secciones principales de tu app en una barra de navegación fija en la parte inferior, cerca del pulgar.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo195.html",
  },
  {
    id: 196,
    titulo: "Subraya los enlaces dentro de los párrafos",
    desc: "Si tienes un enlace en medio de un texto normal, cambiarle el color no es suficiente (especialmente para daltónicos). Subráyalo o ponle un borde inferior sutil.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo196.html",
  },
  {
    id: 197,
    titulo: "Usa claridad para elevar en Modo Oscuro",
    desc: "Las sombras desaparecen en fondos muy oscuros. Para dar la sensación de que un modal o tarjeta 'flota' por encima, haz que su color de fondo gris sea un poco más claro que la base.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo197.html",
  },
  {
    id: 198,
    titulo: "Ofrece 'Deshacer' en vez de confirmar",
    desc: "Los cuadros de confirmación ('¿Estás seguro?') interrumpen el flujo. A veces es mejor realizar la acción destructiva de inmediato y mostrar un toast abajo con un botón de 'Deshacer'.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo198.html",
  },
  {
    id: 199,
    titulo: "Muestra atajos en menús contextuales",
    desc: "Si un elemento del menú desplegable tiene un atajo de teclado, escríbelo alineado a la derecha en color gris (ej. 'Ctrl + C'). Educa a tus usuarios sin estorbar.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo199.html",
  },
  {
    id: 200,
    titulo: "Respeta la preferencia de movimiento",
    desc: "Usa la media query '@media (prefers-reduced-motion)' para desactivar animaciones pesadas en usuarios que tienen configurado su sistema operativo para minimizar el movimiento.",
    demo_url: "codigo_git-hub/codigo_consejos_ui/consejo200.html",
  },
];
